### ISSUE TITLE
"azuremetadata" output contains upper-case letters

### ISSUE THREAD

**Issue by amach4** [SUSE/susecloud-repocheck#55]
**The "location" output from "azuremetadata" command contains upper-case letters:**

sles-sap-12-sp5-gen2:~ # azuremetadata 

    location: GermanyWestCentral

**Result:**

The "get_rmt_servers" function compares the _region_ output which is not identical and "/etc/hosts" entry will be re-created:

Output:

2024-01-31 09:12:05,455 INFO: Checking RMT server entry is for correct region.
2024-01-31 09:12:05,456 WARNING: PROBLEM: RMT server entry is for wrong region.
2024-01-31 09:12:05,456 WARNING: PROBLEM: Multiple or incorrect rmt records exist, deleting.

sles-sap-12-sp5-gen2:~ # zypper info python3-azuremetadata
Refreshing service 'Advanced_Systems_Management_Module_x86_64'.
Refreshing service 'Containers_Module_x86_64'.
Refreshing service 'HPC_Module_x86_64'.
Refreshing service 'Legacy_Module_x86_64'.
Refreshing service 'Public_Cloud_Module_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Live_Patching_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_for_SAP_Applications_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Software_Development_Kit_x86_64'.
Refreshing service 'Toolchain_Module_x86_64'.
Refreshing service 'Web_and_Scripting_Module_x86_64'.
Loading repository data...
Reading installed packages...

Information for package python3-azuremetadata:
----------------------------------------------
Repository     : SLE-Module-Public-Cloud12-Updates                        
Name           : python3-azuremetadata                                    
Version        : 5.1.4-1.20.1                                             
Arch           : noarch                                                   
Vendor         : SUSE LLC <https://www.suse.com/>                         
Support Level  : Level 3                                                  
Installed Size : 63.9 KiB                                                 
Installed      : Yes                                                      
Status         : up-to-date                                               
Source package : python3-azuremetadata-5.1.4-1.20.1.src                   
Summary        : Python module for collecting instance metadata from Azure
Description    :                                                          
    A module for collecting instance metadata from Microsoft Azure.

**Resolution:**

For Azure adding the following line fixed this:

diff --git a/sc-repocheck.py b/sc-repocheck.py
index 7e188da..8f838fe 100755
--- a/sc-repocheck.py
+++ b/sc-repocheck.py
@@ -3201,6 +3201,7 @@ def get_os_version():
 
 def get_rmt_servers(framework, region):
     """Get RMT servers for region in particular framework."""
**+    region = region.lower()**
     rmt_servers = []
     rmt_dict = (json.loads(pint_data[framework]))
     for server in rmt_dict:

**Comment by rfparedes** [comment]
Thanks for reporting.  Sorry for the delay getting around to this.  This is fixed.
