### ISSUE TITLE
Registration via Proxy server.

### ISSUE THREAD

**Issue by MrTiptop** [SUSE/susecloud-repocheck#57]
Hello, i need a better understanding of how to register when using proxy server. /etc/hosts file is updated with 
INFO:Modified /etc/hosts, added: 54.93.131.24	smt-ec2.susecloud.net	smt-ec2

now in theory, there is no need to leverage the proxy server to do dns resolution as the hosts file contains IP address, but for some reason it is still asking proxy to do this, which will never work as the domain "smt-ec2.susecloud.net" is not publicly resolvable.

cat /etc/sysconfig/proxy
## Config:      kde,profiles
PROXY_ENABLED="yes"
 
#Proxy
export HTTPS_PROXY=http://proxy.net:3128
export https_proxy=http://proxy.net:3128
export HTTP_PROXY=http://proxy.net:3128
export http_proxy=http://proxy.net:3128
export no_proxy=169.254.169.254,s3.amazonaws.com,*.s3.amazonaws.com,com.amazonaws.eu-west-1.s3,*.com.amazonaws.eu-west-1.s3,s3-eu-west-1.amazonaws.com,*.s3-eu-west-1.amazonaws.com,s3.dualstack.eu-west-1.amazonaws.com,*.s3.dualstack.eu-west-1.amazonaws.com,s3.us-east-1.amazonaws.com,*.s3.us-east-1.amazonaws.com,s3-external-1.amazonaws.com,*.s3-external-1.amazonaws.com,s3.dualstack.us-east-1.amazonaws.com,*.s3.dualstack.us-east-1.amazonaws.com,s3.eu-west-1.amazonaws.com,*.s3.eu-west-1.amazonaws.com
export NO_PROXY=169.254.169.254,s3.amazonaws.com,*.s3.amazonaws.com,com.amazonaws.eu-west-1.s3,*.com.amazonaws.eu-west-1.s3,s3-eu-west-1.amazonaws.com,*.s3-eu-west-1.amazonaws.com,s3.dualstack.eu-west-1.amazonaws.com,*.s3.dualstack.eu-west-1.amazonaws.com,s3.us-east-1.amazonaws.com,*.s3.us-east-1.amazonaws.com,s3-external-1.amazonaws.com,*.s3-external-1.amazonaws.com,s3.dualstack.us-east-1.amazonaws.com,*.s3.dualstack.us-east-1.amazonaws.com,s3.eu-west-1.amazonaws.com,*.s3.eu-west-1.amazonaws.com

**Comment by rfparedes** [comment]
Closing issue.  This is not a question regarding the tool but a support question for registering an instance.
